remote_theme: zendesk/jekyll-theme-zendesk-garden@main


sidebar: 
  - MS-Home




url: "https://scripts.m2s.uk/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap



version: v0.6.0
