remote_theme: zendesk/jekyll-theme-zendesk-garden@main


sidebar: 
  - MS-Home
  - MS-Tools-OneLiners
  - MS-SearchBase
  - label: Reporting
    children:
      - MS-Reporting-LogGroupMemberships
  - label: Tools
    children:
      - MS-Tools-ColourPing   
      - MS-Tools-MassMessage
  - MS-License



url: "https://scripts.m2s.uk/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap



version: v0.5.0
