remote_theme: zendesk/jekyll-theme-zendesk-garden@main


sidebar: 
  - MS-Home
  - label: Reporting
    children:
      - MS-Reporting-LogGroupMemberships
  - label: Misc

  - LICENSE







version: v0.5.0
